# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Build documentation in the docs/ directory with MkDocs
mkdocs:
  configuration: mkdocs.yml

# Optionally build your docs in additional formats such as PDF
formats: []

# Python configuration
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Python requirements
python:
  install:
    - requirements: requirements.txt
